#!/usr/bin/env bash
# medha_dev_setup.sh — dev environment setup for medha contributors.
#
# This script is for people who BUILD and RUN the medha stack itself.
# If you just want to connect an existing project to a running medha instance,
# use bin/connect.sh instead.
#
# Usage:
#   ./medha_dev_setup.sh                # interactive
#   ./medha_dev_setup.sh --pull <tag>   # skip build, pull a pre-built ghcr.io image
#   ./medha_dev_setup.sh --force        # overwrite existing .env / .env.mcp
#
# Non-interactive: set env vars before running:
#   BIFROST_URL=http://... LLM_MODEL=... POSTGRES_HOST=... ./medha_dev_setup.sh
#
# Steps:
#   1. Check prerequisites
#   2. Create .env  (full service config)
#   3. Create .env.mcp  (same config + AGENTMEMORY_URL for hooks)
#   4. Start the stack (docker compose -f docker-compose.local.yml)
#   5. Wait for the API to be healthy
#   6. Connect this repo to itself via bin/install.sh
#   7. Seed procedural memory from CLAUDE.md

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_ROOT"

# ── colours ────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
    C_BLUE='\033[0;34m'; C_GREEN='\033[0;32m'
    C_YELLOW='\033[0;33m'; C_RED='\033[0;31m'; C_RESET='\033[0m'
else
    C_BLUE=''; C_GREEN=''; C_YELLOW=''; C_RED=''; C_RESET=''
fi
info() { printf "${C_BLUE}•${C_RESET} %s\n" "$*"; }
ok()   { printf "${C_GREEN}✓${C_RESET} %s\n" "$*"; }
warn() { printf "${C_YELLOW}!${C_RESET} %s\n" "$*"; }
die()  { printf "${C_RED}ERROR:${C_RESET} %s\n" "$*" >&2; exit 1; }
ask()  {
    local var="$1" prompt="$2" default="${3:-}"
    if [ -n "${!var:-}" ]; then
        printf '  %s [using env: %s]\n' "$prompt" "${!var}" >&2
        printf '%s' "${!var}"; return
    fi
    if [ -n "$default" ]; then printf '  %s [%s]: ' "$prompt" "$default" >&2
    else printf '  %s: ' "$prompt" >&2; fi
    IFS= read -r _v </dev/tty
    printf '%s' "${_v:-$default}"
}

# ── flags ──────────────────────────────────────────────────────────────────
PULL_TAG=""
FORCE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --pull)  PULL_TAG="${2:?'--pull requires a tag'}"; shift 2 ;;
        --force) FORCE=true; shift ;;
        -h|--help)
            sed -n '2,18p' "$0" | grep '^#' | sed 's/^# \?//'
            exit 0 ;;
        *) die "Unknown flag: $1" ;;
    esac
done

# ── 1. prerequisites ────────────────────────────────────────────────────────
echo ""
info "Checking prerequisites…"
check_cmd() { command -v "$1" >/dev/null 2>&1 || die "$1 is required but not found"; }
check_cmd docker
check_cmd jq
check_cmd curl
check_cmd openssl
docker compose version >/dev/null 2>&1 || die "docker compose v2 required"
ok "Prerequisites OK"

# ── 2. create .env ─────────────────────────────────────────────────────────
echo ""
if [ -f "$REPO_ROOT/.env" ] && [ "$FORCE" = false ]; then
    warn ".env already exists — loading existing values (use --force to overwrite)"
    set -a; source "$REPO_ROOT/.env" 2>/dev/null || true; set +a
else
    info "Configuration"
    echo "  Press Enter to accept the default shown in [brackets]."
    echo ""

    BIFROST_URL=$(ask BIFROST_URL      "Bifrost gateway URL"              "http://192.168.2.91:8080")
    BIFROST_API_KEY=$(ask BIFROST_API_KEY "Bifrost API key (optional)"    "")
    LLM_MODEL=$(ask LLM_MODEL          "LLM model"                        "deepseek/deepseek-v4-pro")
    EMBEDDING_MODEL=$(ask EMBEDDING_MODEL "Embedding model (blank = local hashing)" "qwen/qwen3-embedding-8b")

    echo ""
    POSTGRES_HOST=$(ask POSTGRES_HOST  "PostgreSQL host"   "localhost")
    POSTGRES_PORT=$(ask POSTGRES_PORT  "PostgreSQL port"   "5432")
    POSTGRES_DB=$(ask POSTGRES_DB      "PostgreSQL DB"     "medha")
    POSTGRES_USER=$(ask POSTGRES_USER  "PostgreSQL user"   "medha")
    POSTGRES_PASSWORD=$(ask POSTGRES_PASSWORD "PostgreSQL password" "medha-password")

    echo ""
    NEO4J_ENABLED=$(ask NEO4J_ENABLED  "Enable Neo4j? (true/false)"  "false")
    NEO4J_URI="bolt://localhost:7687"; NEO4J_USERNAME="neo4j"; NEO4J_PASSWORD=""
    if [ "$NEO4J_ENABLED" = "true" ]; then
        NEO4J_URI=$(ask NEO4J_URI           "Neo4j URI"      "bolt://localhost:7687")
        NEO4J_USERNAME=$(ask NEO4J_USERNAME "Neo4j username" "neo4j")
        NEO4J_PASSWORD=$(ask NEO4J_PASSWORD "Neo4j password" "")
    fi

    PORT="${PORT:-3111}"
    VIEWER_PORT="${VIEWER_PORT:-3113}"
    AGENTMEMORY_SECRET="${AGENTMEMORY_SECRET:-$(openssl rand -hex 32)}"

    info "Writing .env…"
    cat > "$REPO_ROOT/.env" <<ENV
# Generated by medha_setup.sh

PORT=$PORT
VIEWER_PORT=$VIEWER_PORT
LOG_LEVEL=info

POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
POSTGRES_SSLMODE=disable

NEO4J_URI=$NEO4J_URI
NEO4J_USERNAME=$NEO4J_USERNAME
NEO4J_PASSWORD=$NEO4J_PASSWORD
NEO4J_ENABLED=$NEO4J_ENABLED

QUEUE_BACKEND=memory
RABBITMQ_URL=amqp://guest:guest@localhost:5672/

PYTHON_SERVICE_URL=http://localhost:5000

AGENTMEMORY_AUTO_COMPRESS=false
AGENTMEMORY_SLOTS=false
AGENTMEMORY_REFLECT=false
CONSOLIDATION_ENABLED=true
LESSON_DECAY_ENABLED=true

DECAY_RATE_PER_DAY=0.95
DECAY_EVICTION_THRESHOLD=0.1
DECAY_REVIEW_LOW=0.1
DECAY_REVIEW_HIGH=0.3

AGENTMEMORY_SECRET=$AGENTMEMORY_SECRET

OTEL_SERVICE_NAME=agent-mem-go

PY_PORT=5000
PY_LOG_LEVEL=info
BIFROST_URL=$BIFROST_URL
BIFROST_API_KEY=$BIFROST_API_KEY
LLM_MODEL=$LLM_MODEL
COMPRESS_MODEL=$LLM_MODEL
SUMMARIZE_MODEL=$LLM_MODEL
EXTRACT_MODEL=$LLM_MODEL
EMBEDDING_MODEL=$EMBEDDING_MODEL

WIKIPEDIA_RATE_LIMIT=0.5
DIFFBOT_API_KEY=
ENV
    ok ".env written"
fi

# Load final values for the steps below
set -a; source "$REPO_ROOT/.env"; set +a
PORT="${PORT:-3111}"
AGENTMEMORY_URL="http://localhost:${PORT}"

# ── 3. create .env.mcp ─────────────────────────────────────────────────────
# .env.mcp = .env + AGENTMEMORY_URL.
# Used by: the standalone MCP container (full config) and hooks (URL + secret).
if [ ! -f "$REPO_ROOT/.env.mcp" ] || [ "$FORCE" = true ]; then
    info "Writing .env.mcp…"
    cp "$REPO_ROOT/.env" "$REPO_ROOT/.env.mcp"
    printf '\n# Hook config\nAGENTMEMORY_URL=%s\n' "$AGENTMEMORY_URL" >> "$REPO_ROOT/.env.mcp"
    ok ".env.mcp written"
else
    warn ".env.mcp already exists — skipping (use --force to overwrite)"
fi

# ── 4. start the stack ─────────────────────────────────────────────────────
echo ""
info "Starting medha services…"
if [ -n "$PULL_TAG" ]; then
    info "  Pulling image tag: $PULL_TAG"
    IMAGE_TAG="$PULL_TAG" docker compose -f docker-compose.local.yml up -d --no-build
else
    docker compose -f docker-compose.local.yml up -d --build
fi
ok "docker compose started"

# ── 5. wait for health ─────────────────────────────────────────────────────
echo ""
info "Waiting for API at $AGENTMEMORY_URL/agentmemory/health…"
for i in $(seq 1 30); do
    HTTP=$(curl -s -o /dev/null -w "%{http_code}" --max-time 3 \
        -H "Authorization: Bearer ${AGENTMEMORY_SECRET:-}" \
        "$AGENTMEMORY_URL/agentmemory/health" 2>/dev/null || echo "000")
    if [ "$HTTP" = "200" ]; then ok "API healthy (${i}s)"; break; fi
    if [ "$i" = "30" ]; then
        warn "API not healthy after 30s — continuing anyway"
        warn "Check: docker compose -f docker-compose.local.yml logs"
        break
    fi
    printf '  [%d/30] waiting…\r' "$i"
    sleep 1
done

# ── 6. connect this repo to itself ─────────────────────────────────────────
echo ""
info "Connecting this repo to itself (bin/connect.sh .)…"
AGENTMEMORY_URL="$AGENTMEMORY_URL" \
AGENTMEMORY_SECRET="${AGENTMEMORY_SECRET:-}" \
AGENTMEMORY_PROJECT="${AGENTMEMORY_PROJECT:-$(basename "$REPO_ROOT")}" \
    "$REPO_ROOT/bin/connect.sh" "$REPO_ROOT"

# ── 7. seed CLAUDE.md ──────────────────────────────────────────────────────
echo ""
if [ -x "$REPO_ROOT/bin/agentmem-seed-procedural" ]; then
    info "Seeding procedural memory from CLAUDE.md…"
    AGENTMEMORY_URL="$AGENTMEMORY_URL" \
    AGENTMEMORY_SECRET="${AGENTMEMORY_SECRET:-}" \
        "$REPO_ROOT/bin/agentmem-seed-procedural" "$REPO_ROOT/CLAUDE.md" \
        && ok "CLAUDE.md seeded" \
        || warn "Seeding returned non-zero — check output above"
fi

# ── done ───────────────────────────────────────────────────────────────────
echo ""
printf "${C_GREEN}medha dev environment ready.${C_RESET}\n\n"

printf '  API:    %s/agentmemory/health\n' "$AGENTMEMORY_URL"
printf '  Viewer: http://localhost:%s\n'   "${VIEWER_PORT:-3113}"
printf '  MCP:    http://localhost:3114/mcp\n'
echo ""
printf '  Logs:   docker compose -f docker-compose.local.yml logs -f\n'
printf '  Stop:   docker compose -f docker-compose.local.yml down\n'
echo ""
